module github.com/benjvi/osb-checker

go 1.13

require (
	github.com/antihax/optional v1.0.0
	github.com/benjvi/osb-checker/autogenerated/go-client v0.0.0-20201118111639-96c853d08fcc
	github.com/ghodss/yaml v1.0.0
	github.com/gopherjs/gopherjs v0.0.0-20200217142428-fce0ec30dd00 // indirect
	github.com/gorilla/mux v1.8.0
	github.com/kr/pretty v0.2.1 // indirect
	github.com/kr/text v0.2.0 // indirect
	github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e // indirect
	github.com/openservicebrokerapi/osb-checker v0.0.0-20190827084956-e6d47cbaed87
	github.com/satori/go.uuid v1.2.0
	github.com/smartystreets/assertions v1.2.0 // indirect
	github.com/smartystreets/goconvey v1.6.4
	gopkg.in/check.v1 v1.0.0-20200902074654-038fdea0a05b // indirect
	gopkg.in/yaml.v2 v2.3.0 // indirect
)
